name: CodeShield CI

on:
  push:
    branches:
      - main
      - codeshield-dev
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Scan repository for secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build -t codeshield:test .

      - name: Run tests
        run: docker run --rm codeshield:test pytest -q

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: codeshield:test
          format: table
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Configure AWS credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::851725640243:role/CodeShield-github-actions-role
          aws-region: ap-south-1

      - name: Verify AWS identity
        if: github.event_name == 'push'
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        if: github.event_name == 'push'
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Docker image
        if: github.event_name == 'push'
        run: |
          docker tag codeshield:test 851725640243.dkr.ecr.ap-south-1.amazonaws.com/codeshield:${{ github.sha }}
          docker tag codeshield:test 851725640243.dkr.ecr.ap-south-1.amazonaws.com/codeshield:latest

      - name: Push Docker image to ECR
        if: github.event_name == 'push'
        run: |
          docker push 851725640243.dkr.ecr.ap-south-1.amazonaws.com/codeshield:${{ github.sha }}
          docker push 851725640243.dkr.ecr.ap-south-1.amazonaws.com/codeshield:latest